spring:
  application:
    name: tp2suggestionbox
  datasource:
    url: jdbc:h2:mem:fatec;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: fatec
    password: aluno
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: br.com.fatecararas.tp2suggestionbox.resources
  pathsToMatch: /**
api:
  common:
    version: 1.0.0
    title: DevNotes
    description: API de compartilhamento de notas de desenvolvimento de software e afins.
    termsOfService: Em progresso...
    license: Nossa Lincesa
    licenseUrl: Em progresso...
    externalDocDesc: WIKI PAGE em progresso
    externalDocUrl: WIKI URL em progresso...
    contact:
      name: Esdras B Silva
      url: esdras.youtrack.com
      email: esdras.silva9@fatec.sp.gov.br

